### ISSUE TITLE
Is it possible to access VGA memory with this SDK?

### ISSUE THREAD

**Issue by SeedyROM** [jayschwa/dos.zig#1]
I'm still learning a ton about real mode and protected mode, so maybe I'm not aware of how to do this. But when I attempt to use a far pointer to VGA memory at `0xA0000000` I get a a General Protection Fault. Which makes sense, these are protected mode executables... is there anyway I could access VGA memory?! I've seen some hacks that use ASM to set the VGA memory as not protected [as seen here as the last post](https://board.flatassembler.net/topic.php?t=6460).

Maybe this is just outside the goal of this project?

**Comment by SeedyROM** [comment]
Okay, I was able to write the VRAM by creating my own VideoMemBlock struct that used DMPI allocations for a VRAM.

The source is here: 
https://git.vortan.dev/SeedyROM/neon-nexus/src/commit/783f9587bda2b35ed9fc4e2d24a19aba01fea360/src/nexus/dos/dpmi/mem.zig#L89-L152

**Comment by jayschwa** [comment]
While the package doesn't provide any VGA help right now, it's something I'd like to have eventually. I'm glad to see you got it working in your fork!
